source "https://rubygems.org"

gem 'sinatra',           '1.4.8'
gem 'data_mapper',       '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'json',              '~>1.6'
gem 'thin',              '1.7.0'
gem 'slim',              '3.0.8'
gem 'shotgun',           '0.9.2'
gem 'money',             '6.9.0'
gem 'monetize',          '1.7.0'
gem 'google_currency',   '3.3.0'